import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { physicalDocumentSchema, type PhysicalDocument } from '../shared/domain/document';
import { APPLICABILITY_FIELDS, createProposedRoomApplicability, createUnknownRoomApplicability, roomApplicabilitySchema } from '../shared/domain/applicability';
import { unknownMeasurement } from '../shared/domain/measurements';
import { calculateQuantities } from '../shared/quantities/engine';
import { calculationSchema } from '../shared/quantities/result';
import { evaluateQuantityReadiness } from '../shared/quantities/readiness';
import { QUANTITY_POLICY_VERSION_V2, type QuantityRequest, type QuantitySelection } from '../shared/quantities/policy';
import { createQuantitySnapshot, evaluateQuantities, verifyQuantitySnapshot, quantitySnapshotSchema } from '../shared/quantities/snapshot';
import { canonicalJson } from '../shared/quantities/canonicalJson';
import { q001, room, measured, request, allSelections, AT, freezeDeep } from './fixtures/physical';

function document(confirmed = true): PhysicalDocument {
  const doc = q001();
  doc.quantityPolicyVersion = QUANTITY_POLICY_VERSION_V2;
  const profile = createProposedRoomApplicability();
  if (confirmed) for (const field of APPLICABILITY_FIELDS) profile[field].confirmation = { status: 'confirmed', confirmedAt: AT };
  doc.calculationContract = { version: 'room-applicability-v1', rooms: { 'room-1': profile } };
  return doc;
}
function selected(doc: PhysicalDocument, selections = allSelections(doc)): QuantityRequest {
  return { ...request(selections), policy: { version: QUANTITY_POLICY_VERSION_V2, openingMeasureBasis: 'finished', crownFullHeightGaps: [] } };
}
function calculation(doc: PhysicalDocument, requested = selected(doc)) {
  const result = calculateQuantities(doc, requested);
  assert.ok(result.ok, JSON.stringify(result));
  return result.calculation;
}
const squareFeet = (mm2: number) => mm2 / (304.8 * 304.8);
const output = (doc: PhysicalDocument, id: string, requested = selected(doc)) => calculation(doc, requested).outputs.find(value => value.output === id)!;
const metadata = (kind: 'evaluation' | 'confirmed' = 'confirmed') => ({ id: 'm3b-capture', createdAt: AT, kind });

// Captured with the unmodified v1 engine before M3B implementation, not generated by this test.
const historicalSnapshot = JSON.parse(readFileSync(new URL('./fixtures/m3b-v1-snapshot.json', import.meta.url), 'utf8'));

test('M3B frozen v1 calculation and captured snapshot remain byte/content identical and verifiable', async () => {
  assert.deepEqual(await verifyQuantitySnapshot(historicalSnapshot), { ok: true });
  const regenerated = await createQuantitySnapshot(historicalSnapshot.sourceDocument,
    historicalSnapshot.evaluation.calculation.request, historicalSnapshot.instance, historicalSnapshot.measurementEvents);
  assert.ok(regenerated.ok);
  assert.equal(canonicalJson(regenerated.snapshot), canonicalJson(historicalSnapshot));
  assert.equal(regenerated.snapshot.snapshotSchemaVersion, 'quantity-snapshot-v1');
  assert.equal(Object.hasOwn(regenerated.snapshot.evaluation.calculation.records[0].readiness, 'applicability'), false);
});

test('M3B exact 12 by 10 ceiling-height acceptance keeps independent 120 square-foot surfaces', () => {
  const doc = document(); doc.openings = [];
  const work: QuantitySelection[] = [
    { output: 'floor-area', roomIds: ['room-1'], wasteFraction: 0 },
    { output: 'ceiling-area', roomIds: ['room-1'], wasteFraction: 0 },
    { output: 'gross-wall-area', wallFaceIds: doc.rooms[0].wallFaces.map(face => face.id), wasteFraction: 0 },
  ];
  const requested = selected(doc, work);
  for (const [height, wallArea] of [['8 ft', 352], ['9 ft', 396], ['2.7432 m', 396], ['8 ft 6 1/2 in', 44 * (8 + 6.5 / 12)]] as const) {
    doc.rooms[0].ceilingHeight = measured(height);
    assert.equal(squareFeet(output(doc, 'floor-area', requested).total!.net), 120);
    assert.equal(squareFeet(output(doc, 'ceiling-area', requested).total!.net), 120);
    assert.ok(Math.abs(squareFeet(output(doc, 'gross-wall-area', requested).total!.net) - wallArea) < 1e-10);
  }
  doc.rooms[0].ceilingHeight = unknownMeasurement('Height cleared');
  assert.equal(squareFeet(output(doc, 'floor-area', requested).total!.net), 120);
  assert.equal(squareFeet(output(doc, 'ceiling-area', requested).total!.net), 120);
  assert.equal(output(doc, 'gross-wall-area', requested).total, null);
  assert.equal(output(doc, 'gross-wall-area', requested).status, 'blocked');
});

test('M3B proposed supported models keep dependent outputs provisional even with confirmed measurements', () => {
  const doc = document(false), result = calculation(doc);
  for (const id of ['ceiling-area', 'gross-wall-area', 'net-wall-area', 'crown', 'door-casing', 'window-casing']) {
    assert.equal(result.outputs.find(value => value.output === id)!.status, 'provisional', id);
  }
  for (const id of ['floor-area', 'baseboard', 'base-shoe', 'opening-inventory']) {
    assert.equal(result.outputs.find(value => value.output === id)!.status, 'complete', id);
  }
  assert.equal(doc.rooms[0].ceilingHeight.state === 'known' && doc.rooms[0].ceilingHeight.provenance.confirmation.status, 'confirmed');
});

test('M3B unknown imported applicability blocks only dependent work and names exact room/profile paths', () => {
  const doc = document(); doc.calculationContract!.rooms['room-1'] = createUnknownRoomApplicability('No finish-model evidence in source');
  const result = calculation(doc);
  for (const id of ['floor-area', 'baseboard', 'base-shoe', 'opening-inventory']) assert.equal(result.outputs.find(value => value.output === id)!.status, 'complete', id);
  for (const id of ['ceiling-area', 'gross-wall-area', 'net-wall-area', 'crown', 'door-casing', 'window-casing']) assert.equal(result.outputs.find(value => value.output === id)!.status, 'blocked', id);
  const ceiling = result.records.find(value => value.output === 'ceiling-area')!;
  assert.equal(ceiling.amounts, null);
  assert.ok(ceiling.errors.some(error => error.code === 'APPLICABILITY_UNKNOWN'
    && JSON.stringify(error.path) === JSON.stringify(['calculationContract', 'rooms', 'room-1', 'ceiling'])));
});

test('M3B unsupported ceiling never reuses projected floor area and preserves independent supported walls/casing', () => {
  const doc = document(), before = structuredClone(doc.rooms);
  doc.calculationContract!.rooms['room-1'].ceiling = { value: 'unsupported', source: 'manual',
    confirmation: { status: 'unconfirmed' }, detail: 'Vaulted ceiling with measured height retained; slope geometry unavailable' };
  const result = calculation(doc);
  assert.equal(result.outputs.find(value => value.output === 'ceiling-area')!.total, null);
  for (const id of ['floor-area', 'gross-wall-area', 'net-wall-area', 'crown', 'door-casing']) assert.equal(result.outputs.find(value => value.output === id)!.status, 'complete', id);
  assert.deepEqual(doc.rooms, before);
});

test('M3B nonuniform walls block walls/casing and full-height crown gaps, not ordinary crown/floor runs', () => {
  const doc = document();
  doc.calculationContract!.rooms['room-1'].walls = { value: 'unsupported', source: 'manual',
    confirmation: { status: 'unconfirmed' }, detail: 'Wall finish heights vary' };
  for (const id of ['gross-wall-area', 'net-wall-area', 'door-casing', 'window-casing']) assert.equal(output(doc, id).status, 'blocked', id);
  for (const id of ['floor-area', 'ceiling-area', 'baseboard', 'base-shoe', 'crown']) assert.equal(output(doc, id).status, 'complete', id);
  doc.openings[0].height = measured('8 ft');
  const requested = selected(doc); requested.policy.crownFullHeightGaps = [{ wallFaceId: 'room-1:top', openingId: 'door' }];
  assert.equal(output(doc, 'crown', requested).status, 'blocked');
  assert.equal(output(doc, 'crown', requested).completeness, 'partial');
});

test('M3B crown-path declaration is independent of ceiling and wall applicability', () => {
  const doc = document(); doc.calculationContract!.rooms['room-1'].crownPath = { value: 'unsupported', source: 'manual',
    confirmation: { status: 'unconfirmed' }, detail: 'Stepped crown path' };
  assert.equal(output(doc, 'crown').status, 'blocked');
  for (const id of ['floor-area', 'ceiling-area', 'gross-wall-area', 'baseboard', 'door-casing']) assert.equal(output(doc, id).status, 'complete', id);
});

test('M3B partial selected totals expose unsupported rooms and retain provisional included subtotal', () => {
  const doc = document(false); doc.rooms.push(room('room-2'));
  doc.calculationContract!.rooms['room-2'] = createUnknownRoomApplicability();
  const result = output(doc, 'ceiling-area', selected(doc, [{ output: 'ceiling-area', roomIds: ['room-1', 'room-2'], wasteFraction: 0 }]));
  assert.equal(result.total, null); assert.equal(result.status, 'blocked'); assert.equal(result.completeness, 'partial');
  assert.equal(result.subtotalStatus, 'provisional'); assert.equal(squareFeet(result.subtotal!.net), 120);
  assert.deepEqual(result.includedTargetIds, ['room:"room-1"']); assert.deepEqual(result.excludedTargetIds, ['room:"room-2"']);
});

test('M3B applicability and group contracts validate exact room ownership without inferring topology', () => {
  const doc = document(); doc.rooms.push(room('room-2'));
  doc.calculationContract!.rooms['room-2'] = createProposedRoomApplicability();
  doc.editorContract = { version: 'sketch-editor-v1', groups: [{ id: 'group-a', roomIds: ['room-1', 'room-2'] }] };
  assert.ok(physicalDocumentSchema.safeParse(doc).success);
  for (const mutate of [
    (d: PhysicalDocument) => { delete d.calculationContract!.rooms['room-2']; },
    (d: PhysicalDocument) => { d.calculationContract!.rooms.ghost = createProposedRoomApplicability(); },
    (d: PhysicalDocument) => { d.editorContract!.groups[0].roomIds.push('room-1'); },
    (d: PhysicalDocument) => { d.editorContract!.groups.push({ id: 'group-b', roomIds: ['room-1'] }); },
    (d: PhysicalDocument) => { d.editorContract!.groups[0].roomIds.push('ghost'); },
    (d: PhysicalDocument) => { d.editorContract!.groups.push({ id: 'group-a', roomIds: [] }); },
  ]) { const changed = structuredClone(doc); mutate(changed); assert.equal(physicalDocumentSchema.safeParse(changed).success, false); }
  for (const malformed of [null, [], new Date(), 'flat']) {
    const changed = structuredClone(doc) as any; changed.calculationContract.rooms = malformed;
    assert.equal(physicalDocumentSchema.safeParse(changed).success, false);
  }
  const unknown = createUnknownRoomApplicability();
  assert.equal(roomApplicabilitySchema.safeParse({ ...unknown, ceiling: { ...unknown.ceiling, detail: ' ' } }).success, false);
  assert.equal(roomApplicabilitySchema.safeParse({ ...unknown, ceiling: { ...unknown.ceiling, confirmation: { status: 'confirmed', confirmedAt: AT } } }).success, false);
});

test('M3B special own room IDs retain typed applicability and prototype safety', () => {
  const doc = document(); doc.rooms = [room('__proto__')]; doc.openings = [];
  doc.calculationContract!.rooms = Object.fromEntries([['__proto__', createProposedRoomApplicability()]]);
  assert.ok(physicalDocumentSchema.safeParse(doc).success);
  assert.equal(output(doc, 'ceiling-area').status, 'provisional');
  assert.equal(Object.hasOwn(doc.calculationContract!.rooms, '__proto__'), true);
  assert.equal(({} as any).ceiling, undefined);
});

test('M3B policy dispatch rejects missing, mismatched and downgrade attempts without source rewrites', () => {
  const doc = document(), before = canonicalJson(doc);
  const downgrade = calculateQuantities(doc, request(allSelections(doc))); assert.equal(downgrade.ok, false);
  const missing = structuredClone(doc); delete missing.calculationContract;
  assert.equal(calculateQuantities(missing, selected(doc)).ok, false);
  const undeclared = structuredClone(doc); undeclared.quantityPolicyVersion = null;
  assert.equal(calculateQuantities(undeclared, selected(doc)).ok, false);
  const wrong = selected(doc); (wrong.policy as any).version = 'rectangular-flat-v99';
  assert.equal(calculateQuantities(doc, wrong).ok, false);
  assert.equal(canonicalJson(doc), before);
  const computed = structuredClone(calculation(doc));
  assert.equal(computed.schemaVersion, 'quantity-result-v2'); assert.equal(computed.engineVersion, 'rectangular-engine-v2');
  computed.schemaVersion = 'quantity-result-v1'; assert.equal(calculationSchema.safeParse(computed).success, false);
});

test('M3B applicability readiness is detached and frozen engine results cannot mutate source declarations', () => {
  const doc = document(false), before = canonicalJson(doc);
  const ready = evaluateQuantityReadiness(doc, selected(doc)); assert.ok(ready.ok);
  ready.outputs.find(value => value.output === 'ceiling-area')!.applicability!.dependencies[0].declaration.detail = 'changed report';
  assert.equal(canonicalJson(doc), before);
  const result = calculation(freezeDeep(doc));
  assert.throws(() => { (result.records.find(value => value.output === 'ceiling-area')!.readiness.applicability!.dependencies[0].declaration as any).value = 'unsupported'; });
  assert.equal(canonicalJson(doc), before);
});

test('M3B fingerprints bind applicability values to geometry and declaration evidence only to content', async () => {
  const doc = document(); const requested = selected(doc);
  const initial = await evaluateQuantities(doc, requested); assert.ok(initial.ok);
  assert.equal(initial.evaluation.fingerprints.geometryScope, 'physical-geometry-v2');
  const evidence = structuredClone(doc); evidence.calculationContract!.rooms['room-1'].ceiling.detail = 'Inspected finished ceiling';
  const next = await evaluateQuantities(evidence, requested); assert.ok(next.ok);
  assert.equal(next.evaluation.fingerprints.geometry, initial.evaluation.fingerprints.geometry);
  assert.notEqual(next.evaluation.fingerprints.content, initial.evaluation.fingerprints.content);
  evidence.calculationContract!.rooms['room-1'].ceiling = createUnknownRoomApplicability().ceiling;
  const changed = await evaluateQuantities(evidence, requested); assert.ok(changed.ok);
  assert.notEqual(changed.evaluation.fingerprints.geometry, initial.evaluation.fingerprints.geometry);
  const view = structuredClone(doc); view.name = 'Renamed'; view.viewport = { scale: 2, panX: 300 };
  view.rooms[0].presentation!.color = 'red'; view.editorContract = { version: 'sketch-editor-v1', groups: [{ id: 'group-a', roomIds: ['room-1'] }] };
  const presentation = await evaluateQuantities(view, requested); assert.ok(presentation.ok);
  assert.deepEqual(presentation.evaluation.fingerprints, initial.evaluation.fingerprints);
});

test('M3B v2 snapshot confirmation gate, version agreement and independent integrity verification', async () => {
  const doc = document(); const requested = selected(doc);
  const captured = await createQuantitySnapshot(doc, requested, metadata()); assert.ok(captured.ok);
  assert.equal(captured.snapshot.snapshotSchemaVersion, 'quantity-snapshot-v2');
  assert.deepEqual(await verifyQuantitySnapshot(captured.snapshot), { ok: true });
  const mixed = structuredClone(captured.snapshot); mixed.snapshotSchemaVersion = 'quantity-snapshot-v1';
  assert.equal(quantitySnapshotSchema.safeParse(mixed).success, false);
  const changed = structuredClone(captured.snapshot); changed.sourceDocument.calculationContract!.rooms['room-1'].ceiling.detail = 'different source evidence';
  assert.equal((await verifyQuantitySnapshot(changed)).ok, false);
  for (const incomplete of [document(false), document()]) {
    if (incomplete.calculationContract!.rooms['room-1'].ceiling.confirmation.status === 'confirmed') {
      incomplete.calculationContract!.rooms['room-1'] = createUnknownRoomApplicability();
    }
    assert.equal((await createQuantitySnapshot(incomplete, selected(incomplete), metadata())).ok, false);
    assert.equal((await createQuantitySnapshot(incomplete, selected(incomplete), metadata('evaluation'))).ok, true);
    assert.equal((await createQuantitySnapshot(incomplete, selected(incomplete, [{ output: 'floor-area', roomIds: ['room-1'], wasteFraction: 0 }]), metadata())).ok, true);
  }
});


test('M3B shared openings use only the selected attachment wall applicability', () => {
  const doc = document(); doc.rooms.push(room('room-2'));
  doc.calculationContract!.rooms['room-2'] = createUnknownRoomApplicability('Other face not reviewed');
  doc.openings = [doc.openings[0]];
  doc.openings[0].attachments.push({ wallFaceId: 'room-2:top', anchor: 'center', offsetMm: doc.openings[0].attachments[0].offsetMm });
  const single = selected(doc, [
    { output: 'net-wall-area', wallFaceIds: ['room-1:top'], wasteFraction: 0 },
    { output: 'door-casing', faces: [{ wallFaceId: 'room-1:top', openingId: 'door' }], wasteFraction: 0 },
    { output: 'opening-inventory', openingIds: ['door'] },
  ]);
  assert.equal(calculation(doc, single).status, 'complete');
  const both = selected(doc, [{ output: 'door-casing', faces: doc.openings[0].attachments.map(attachment => ({
    wallFaceId: attachment.wallFaceId, openingId: 'door',
  })), wasteFraction: 0 }]);
  const result = calculation(doc, both).outputs[0];
  assert.equal(result.total, null); assert.equal(result.completeness, 'partial'); assert.equal(result.subtotalStatus, 'complete');
  assert.equal(result.includedTargetIds.length, 1); assert.equal(result.excludedTargetIds.length, 1);
});
