import assert from 'node:assert/strict';
import test from 'node:test';
import { createLevelDraft,addLevel,selectLevel,assignRoomLevel } from '../client/src/features/physical-draft/levelCommands';
import { createRegistry,insertDraft,selectedDraft,addRoom,editField,commitField,switchUnit,previewDocument,type PhysicalDraft } from '../client/src/features/physical-draft/state';
import { createPhysicalDraftStore,type DraftStorage } from '../client/src/features/physical-draft/store';
import { serializeRegistry,parseRegistry,validateRegistry,PHYSICAL_DRAFT_STORAGE_KEY as KEY,PREVIOUS_PHYSICAL_DRAFT_STORAGE_KEY as PREVIOUS,LEGACY_PHYSICAL_DRAFT_STORAGE_KEY as LEGACY } from '../client/src/features/physical-draft/storage';
import { upgradeExistingDraftToStairs,addStair,stairIn,stairsIn,createRoomLocalPlacement,setStairEndpoint,setStairPlacement,
  editStairField,commitStairField,revertStairField,getStairField,stairFieldError,addLanding,removeLanding,setLandingPlacement,
  addSurfaceOpening,setSurfaceOpeningAttachment,setSurfaceImpact,deleteStair,deleteSurfaceOpening,surfaceOpeningIn,renameStair,type StairFieldTarget } from '../client/src/features/physical-draft/stairCommands';
import { setOutputEnabled,selectAllCurrentTargets,editWaste } from '../client/src/features/physical-draft/takeoffCommands';
import { buildTakeoffReadModel } from '../client/src/features/physical-draft/takeoffReadModel';
import { validateHistoryEvidence } from '../client/src/features/physical-draft/historyEvidence';
const AT='2026-09-09T02:00:00.000Z',ft=304.8,copy=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
class Memory implements DraftStorage{values=new Map<string,string>();reads:string[]=[];writes:string[]=[];quota=false;getItem(k:string){this.reads.push(k);return this.values.get(k)??null;}setItem(k:string,v:string){if(this.quota)throw new Error('quota');this.writes.push(k);this.values.set(k,v);}removeItem(k:string){this.values.delete(k);}}
function room(d:PhysicalDraft,id:string,length:string,width:string,height:string){d=addRoom(d,id,id);for(const [field,value]of [['length',length],['width',width],['ceilingHeight',height]]as const)d=commitField(editField(d,id,field,value),id,field,AT);return d;}
function building(){let d=room(createLevelDraft('old','base'),'basement','12 ft','10 ft','8 ft');d=addLevel(d,'main','Main');d=room(d,'main-room','15 ft','10 ft','9 ft');return selectLevel(d,'base');}
function draft(){return upgradeExistingDraftToStairs(building(),'stairs',AT);}
function lower(){return {state:'modeled' as const,levelId:'base',roomId:'basement',placement:createRoomLocalPlacement(0,0)};}
function upper(){return {state:'modeled' as const,levelId:'main',roomId:'main-room',placement:createRoomLocalPlacement(0,0)};}
function set(d:PhysicalDraft,t:StairFieldTarget,text:string){return commitStairField(editStairField(d,t,text),t,AT);}
function withStair(d=draft()){d=addStair(d,'stair','Main stair',lower(),AT);d=setStairEndpoint(d,'stair','upper',upper(),AT);d=set(d,{kind:'stair',id:'stair',field:'width'},'3 ft');return set(d,{kind:'stair',id:'stair',field:'run'},'6 ft');}
function withHole(d:PhysicalDraft,id='hole',roomId='main-room',surface:'floor'|'ceiling'='floor'){d=addSurfaceOpening(d,id,'Explicit hole',{roomId,surface,placement:createRoomLocalPlacement(ft,ft)},'stair',AT);d=set(d,{kind:'surface-opening',id,field:'width'},'3 ft');return set(d,{kind:'surface-opening',id,field:'length'},'6 ft');}
function usable(d:PhysicalDraft){for(const role of ['lower','upper']as const)for(const surface of ['floor','ceiling']as const)d=setSurfaceImpact(d,'stair',role,surface,{state:'no-deduction'},AT);for(const output of ['floor-area','ceiling-area','gross-wall-area']as const){d=setOutputEnabled(d,output,true);d=selectAllCurrentTargets(d,output);}return d;}
function recover(d:PhysicalDraft){const reg=insertDraft(createRegistry(),d),result=parseRegistry(serializeRegistry(reg));assert.equal(result.status,'recovered');if(result.status==='recovered')assert.deepEqual(result.registry,reg);}
function fixture(d=withStair(),storage=new Memory()){const store=createPhysicalDraftStore(()=>storage);assert.ok(store.dispatch(reg=>insertDraft(reg,d)),store.getSnapshot().error);const current=()=>selectedDraft(store.getSnapshot().registry)!;const update=(fn:(d:PhysicalDraft)=>PhysicalDraft)=>assert.ok(store.updateDraft(current().id,current().localEditRevision,fn),store.getSnapshot().error);const undo=()=>assert.ok(store.undo(current().id,current().localEditRevision,AT),store.getSnapshot().error);const redo=()=>assert.ok(store.redo(current().id,current().localEditRevision,AT),store.getSnapshot().error);const apply=(t:StairFieldTarget,text:string)=>{update(d=>editStairField(d,t,text));update(d=>commitStairField(d,t,AT));};return{store,current,update,undo,redo,storage,apply};}

test('explicit schema4 upgrade retains full current draft and immutable schema3 lineage with pending room/waste edits',()=>{let old=building();old=editField(old,'basement','length','12 ft -');old=setOutputEnabled(old,'floor-area',true);old=selectAllCurrentTargets(old,'floor-area');old=editWaste(old,'floor-area','10.');const prior=copy(old),next=upgradeExistingDraftToStairs(old,'new',AT);assert.deepEqual(old,prior);assert.deepEqual(next.stairUpgradeLineage?.originalDraft,prior);for(const k of ['fields','events','source','levelView','takeoffState']as const)assert.deepEqual(next[k],prior[k]);assert.deepEqual(next.document.rooms,old.document.rooms);assert.equal(next.document.schemaVersion,4);assert.equal(next.request.policy.version,'rectangular-flat-v4');assert.equal(old.request.policy.version,'rectangular-flat-v3');recover(next);});
test('new stair keeps one stable identity shared width/run and unresolved rise without deriving level elevations',()=>{const d=withStair(),s=stairIn(d,'stair');assert.equal(s.width.state,'known');assert.equal(s.run.state,'known');assert.equal(s.totalRise.state,'unknown');assert.deepEqual(stairsIn(d).stairs.map(s=>s.id),['stair']);assert.equal(d.document.schemaVersion,4);if(d.document.schemaVersion===4)assert.ok(d.document.buildingLevels.levels.every(l=>l.finishedFloorElevation.state==='unknown'));recover(d);});
test('invalid dimension raw retains exact text while zero coordinates commit and Enter then blur emits once',()=>{let d=withStair();const t={kind:'stair',id:'stair',field:'width'}as const;d=editStairField(d,t,'3 ft -');const before=copy(d);assert.match(stairFieldError(d,t)!,/syntax/);assert.equal(commitStairField(d,t,AT),d);assert.deepEqual(d,before);d=revertStairField(d,t);const p={kind:'endpoint',id:'stair',role:'lower',field:'x'}as const;d=set(d,p,'0');assert.equal(getStairField(d,p).dirty,false);const events=d.stairEvents?.length;assert.equal(commitStairField(d,p,AT),d);assert.equal(d.stairEvents?.length,events);recover(d);});
test('dirty unit context survives switch and Revert uses current display while preserving physical provenance',()=>{let d=withStair();const t={kind:'stair',id:'stair',field:'run'}as const;const physical=copy(d.document);d=editStairField(d,t,'6 ft -');d=switchUnit(d,'m');assert.equal(getStairField(d,t).unit,'ft');d=revertStairField(d,t);assert.equal(getStairField(d,t).unit,'m');assert.deepEqual(d.document,physical);d=editStairField(d,t,'1.8288');d=commitStairField(d,t,AT);assert.deepEqual(d.document,physical);recover(d);});
test('pending hole size masks only affected net surface while keeping gross basis and unrelated wall quantities',()=>{let d=usable(withHole(withStair()));const before=buildTakeoffReadModel(d);assert.equal(before.outputs.find(o=>o.output==='floor-area')?.total?.net,'252.00 sq ft');d=editStairField(d,{kind:'surface-opening',id:'hole',field:'width'},'3 ft -');const model=buildTakeoffReadModel(d);assert.equal(model.outputs.find(o=>o.output==='floor-area')?.total,null);assert.equal(model.outputs.find(o=>o.output==='floor-area')?.grossBasis,'270.00 sq ft');assert.equal(model.outputs.find(o=>o.output==='ceiling-area')?.total?.net,'270.00 sq ft');assert.equal(model.outputs.find(o=>o.output==='gross-wall-area')?.total?.net,'802.00 sq ft');assert.equal(stairIn(d,'stair').totalRise.state,'unknown');});
test('explicit floor and ceiling holes deduct independently once and have exact source attachment read model',()=>{let d=usable(withHole(withStair()));d=withHole(d,'ceiling-hole','basement','ceiling');d=setSurfaceImpact(d,'stair','upper','floor',{state:'deduct',openingIds:['hole']},AT);d=setSurfaceImpact(d,'stair','lower','ceiling',{state:'deduct',openingIds:['ceiling-hole']},AT);const model=buildTakeoffReadModel(d);assert.equal(model.outputs[0].total?.net,'252.00 sq ft');assert.equal(model.outputs[1].total?.net,'252.00 sq ft');const row=model.outputs[0].rows.find(r=>r.source.roomIds.includes('main-room'))!;assert.deepEqual(row.surfaceContributions[0].source.surfaceOpenings,[{openingId:'hole',roomId:'main-room',surface:'floor'}]);recover(d);});
test('numeric and pointer placements reject demonstrated invalid fit without replacing pending text or canonical position',()=>{let d=withHole(withStair());const t={kind:'surface-placement',id:'hole',roomId:'main-room',surface:'floor',field:'x'}as const;d=editStairField(d,t,'14 ft');const before=copy(d);assert.match(stairFieldError(d,t)!,/internal/);assert.throws(()=>commitStairField(d,t,AT),/internal/);assert.deepEqual(d,before);assert.throws(()=>setStairPlacement(d,'stair','lower',createRoomLocalPlacement(-ft,0),AT),/outside/);assert.deepEqual(d,before);recover(d);});
test('dimension correction may retain invalid fit, never silently move endpoints, and pending coordinates block pointer takeover',()=>{let d=withStair();const prior=copy(stairIn(d,'stair').endpoints);d=set(d,{kind:'stair',id:'stair',field:'run'},'20 ft');assert.deepEqual(stairIn(d,'stair').endpoints,prior);recover(d);const t={kind:'endpoint',id:'stair',role:'lower',field:'x'}as const;d=editStairField(d,t,'1 ft -');assert.throws(()=>setStairPlacement(d,'stair','lower',createRoomLocalPlacement(ft,0),AT),/pending/);assert.equal(getStairField(d,t).text,'1 ft -');});
test('landing dimensions and placement remain independent of stair run and no-deduction areas',()=>{let d=usable(withStair());const before=buildTakeoffReadModel(d).outputs.map(o=>o.total);d=addLanding(d,'stair','lower','landing',AT);d=set(d,{kind:'landing',id:'stair',role:'lower',field:'width'},'3 ft');d=set(d,{kind:'landing',id:'stair',role:'lower',field:'depth'},'3 ft');d=setLandingPlacement(d,'stair','lower',createRoomLocalPlacement(6*ft,0),AT);assert.deepEqual(buildTakeoffReadModel(d).outputs.map(o=>o.total),before);assert.equal(stairIn(d,'stair').run.state==='known'&&stairIn(d,'stair').run.valueMm,6*ft);recover(d);});
test('host ownership guards name dependent endpoints/landings and surface openings; invalid same-level endpoints are rejected',()=>{const d=withHole(withStair()),before=copy(d);assert.throws(()=>assignRoomLevel(d,'basement','main'),/Main stair.*lower/);assert.throws(()=>assignRoomLevel(d,'main-room','base'),/surface opening/);assert.throws(()=>setStairEndpoint(d,'stair','upper',lower(),AT));assert.deepEqual(d,before);});
test('endpoint host changes cannot strand an explicit linked deduction',()=>{let d=withHole(withStair());d=setSurfaceImpact(d,'stair','upper','floor',{state:'deduct',openingIds:['hole']},AT);assert.throws(()=>setStairEndpoint(d,'stair','upper',{state:'unresolved',reason:'Not modeled'},AT),/linked surface deductions/);recover(d);});
test('shared surface attachments reject duplicates and invalid retargeting without partial writes',()=>{const d=withHole(withStair()),opening=surfaceOpeningIn(d,'hole'),before=copy(d);assert.throws(()=>setSurfaceOpeningAttachment(d,'hole',[opening.attachments[0],opening.attachments[0]],AT));assert.deepEqual(d,before);});
test('stair deletion unlinks but preserves holes and Undo/Redo restores exact coordinated identities',()=>{const f=fixture(withHole(withStair()));const original=copy(f.current().document);f.update(d=>deleteStair(d,'stair',AT));assert.equal(stairsIn(f.current()).stairs.length,0);assert.equal(surfaceOpeningIn(f.current(),'hole').associatedStairId,null);f.undo();assert.deepEqual(f.current().document,original);f.redo();assert.equal(stairsIn(f.current()).stairs.length,0);assert.equal(surfaceOpeningIn(f.current(),'hole').associatedStairId,null);recover(f.current());});
test('surface opening deletion makes referenced impacts unresolved and one Undo restores hole and impact atomically',()=>{let d=withHole(withStair());d=setSurfaceImpact(d,'stair','upper','floor',{state:'deduct',openingIds:['hole']},AT);const f=fixture(d),before=copy(d.document);f.update(d=>deleteSurfaceOpening(d,'hole',AT));assert.equal(stairIn(f.current(),'stair').surfaceImpacts.upper.floor.state,'unresolved');assert.equal(stairsIn(f.current()).surfaceOpenings.length,0);f.undo();assert.deepEqual(f.current().document,before);f.redo();assert.equal(stairsIn(f.current()).surfaceOpenings.length,0);recover(f.current());});
test('field/move/landing Undo uses the existing chronological history, preserves unrelated pending fields and reveals target level',()=>{const f=fixture();f.apply({kind:'stair',id:'stair',field:'width'},'4 ft');f.update(d=>editStairField(d,{kind:'stair',id:'stair',field:'run'},'6 ft -'));f.undo();assert.equal(stairIn(f.current(),'stair').width.state==='known'&&stairIn(f.current(),'stair').width.valueMm,3*ft);assert.equal(getStairField(f.current(),{kind:'stair',id:'stair',field:'run'}).text,'6 ft -');assert.equal(f.store.getSnapshot().history.reveal?.stairId,'stair');f.redo();f.update(d=>revertStairField(d,{kind:'stair',id:'stair',field:'run'}));f.update(d=>setStairPlacement(d,'stair','upper',createRoomLocalPlacement(ft,0),AT));f.undo();assert.equal(f.store.getSnapshot().history.reveal?.levelId,'main');assert.equal(f.store.getSnapshot().history.reveal?.endpointRole,'upper');recover(f.current());});
test('conflicting pending field blocks history without popping and view/unit changes preserve redo',()=>{const f=fixture();const t={kind:'stair',id:'stair',field:'width'}as const;f.apply(t,'4 ft');f.update(d=>editStairField(d,t,'5 ft -'));const before=copy(f.current()),label=f.store.getSnapshot().history.undoLabel;assert.equal(f.store.undo(f.current().id,f.current().localEditRevision,AT),false);assert.deepEqual(f.current(),before);assert.equal(f.store.getSnapshot().history.undoLabel,label);f.update(d=>revertStairField(d,t));f.undo();const redo=f.store.getSnapshot().history.redoLabel;f.update(d=>switchUnit(d,'m'));f.update(d=>selectLevel(d,'main'));assert.equal(f.store.getSnapshot().history.redoLabel,redo);f.redo();recover(f.current());});
test('same-value raw resolution, no-op rename and failed placement do not create duplicate committed history',()=>{const f=fixture(),count=f.current().historyEvidence?.events.length??0;f.apply({kind:'stair',id:'stair',field:'width'},'36 in');f.update(d=>renameStair(d,'stair','Main stair'));assert.equal(f.current().historyEvidence?.events.length??0,count);assert.equal(f.store.getSnapshot().history.undoLabel,null);assert.equal(f.store.updateDraft(f.current().id,f.current().localEditRevision,d=>setStairPlacement(d,'stair','lower',createRoomLocalPlacement(20*ft,0),AT)),false);assert.equal(f.store.getSnapshot().history.undoLabel,null);});
test('stale draft revision and unsupported recovery bytes cannot overwrite the selected draft',()=>{const f=fixture(),rev=f.current().localEditRevision;f.update(d=>selectLevel(d,'main'));const before=copy(f.current());assert.equal(f.store.updateDraft(f.current().id,rev,d=>renameStair(d,'stair','Stale')),false);assert.deepEqual(f.current(),before);const bad=new Memory();bad.values.set(KEY,'{"version":"future"}');const store=createPhysicalDraftStore(()=>bad);store.hydrate();assert.equal(store.getSnapshot().cache,'unsupported');assert.equal(store.dispatch(reg=>insertDraft(reg,draft())),false);assert.deepEqual(bad.writes,[]);});
test('v3 recovery falls back to v2 without rewriting it and detects fallback races before first accepted write',()=>{const memory=new Memory(),old=insertDraft(createRegistry(),building()),bytes=serializeRegistry(old);memory.values.set(PREVIOUS,bytes);const store=createPhysicalDraftStore(()=>memory);store.hydrate();assert.deepEqual(memory.reads,[KEY,PREVIOUS]);assert.deepEqual(memory.writes,[]);memory.values.set(PREVIOUS,bytes+' ');const current=selectedDraft(store.getSnapshot().registry)!;assert.ok(store.updateDraft(current.id,current.localEditRevision,d=>selectLevel(d,'main')));assert.equal(store.getSnapshot().cache,'conflict');assert.equal(memory.values.get(PREVIOUS),bytes+' ');assert.equal(memory.values.has(KEY),false);});
test('v3 fallback to v1 preserves all older bytes; failed writes retain accepted memory/history and reload empties only session history',()=>{const f=fixture();f.storage.quota=true;f.update(d=>renameStair(d,'stair','Memory stair'));assert.equal(f.store.getSnapshot().cache,'unavailable');assert.match(f.store.getSnapshot().history.undoLabel!,/name/);f.undo();assert.equal(stairIn(f.current(),'stair').name,'Main stair');const fresh=createPhysicalDraftStore(()=>f.storage);fresh.hydrate();assert.equal(fresh.getSnapshot().history.undoLabel,null);assert.equal(fresh.getSnapshot().cache,'ready');assert.equal(parseRegistry(f.storage.values.get(KEY)!).status,'recovered');});
test('malformed raw target/current text and forged history source are rejected without normalizing captured data',()=>{const f=fixture();f.apply({kind:'stair',id:'stair',field:'width'},'4 ft');f.undo();assert.equal(validateHistoryEvidence(f.current()),null);const registry=copy(f.store.getSnapshot().registry);const stored=registry.drafts[0];stored.stairFields![Object.keys(stored.stairFields!)[0]].raw.text='999 ft';assert.equal(validateRegistry(registry).status,'corrupt');const other=copy(f.store.getSnapshot().registry);other.drafts[0].historyEvidence!.events.at(-1)!.sourceEventId='missing';assert.equal(validateRegistry(other).status,'corrupt');});

test('rotation-only and single-attachment Undo preserve unrelated confirmed measurements and exact evidence',()=>{
  let d=withHole(withStair());const hole=surfaceOpeningIn(d,'hole');hole.attachments.push({roomId:'basement',surface:'ceiling',placement:createRoomLocalPlacement(ft,ft)});
  for(const attachment of hole.attachments)for(const field of ['x','y']as const){const value=attachment.placement[field];if(value.state==='known')value.provenance.confirmation={status:'confirmed',confirmedAt:AT};}
  const f=fixture(d),before=copy(surfaceOpeningIn(d,'hole').attachments);f.update(current=>setSurfaceOpeningAttachment(current,'hole',surfaceOpeningIn(current,'hole').attachments.map((item,index)=>index===0?{...item,placement:{...item.placement,rotation:90}}:item),AT));f.undo();assert.deepEqual(surfaceOpeningIn(f.current(),'hole').attachments,before);f.redo();f.undo();
  const t={kind:'surface-placement',id:'hole',roomId:'main-room',surface:'floor',field:'x'}as const;f.apply(t,'2 ft');f.undo();
  const after=surfaceOpeningIn(f.current(),'hole').attachments;assert.deepEqual(after[1],before[1]);assert.deepEqual(after[0].placement.y,before[0].placement.y);assert.equal(after[0].placement.x.state==='known'&&after[0].placement.x.provenance.confirmation.status,'unconfirmed');recover(f.current());
});

test('same physical pointer placement preserves typed provenance and creates no committed history',()=>{
  let d=withHole(withStair());d=set(d,{kind:'endpoint',id:'stair',role:'lower',field:'x'},'1 ft');
  const f=fixture(d),before=copy(f.current().document);f.update(current=>setStairPlacement(current,'stair','lower',createRoomLocalPlacement(ft,0),AT));
  f.update(current=>setSurfaceOpeningAttachment(current,'hole',[{roomId:'main-room',surface:'floor',placement:createRoomLocalPlacement(ft,ft)}],AT));
  assert.deepEqual(f.current().document,before);assert.equal(f.store.getSnapshot().history.undoLabel,null);recover(f.current());
});

test('adding older-format drafts never downgrades a mixed schema4 recovery envelope',()=>{
  let registry=insertDraft(createRegistry(),withStair());registry=insertDraft(registry,createLevelDraft('second','second-level'));
  assert.equal(registry.version,'mfp-editor-draft-v3');const read=parseRegistry(serializeRegistry(registry));assert.equal(read.status,'recovered');if(read.status==='recovered')assert.deepEqual(read.registry,registry);
});
